"""
Cost model, fitted to measurements — not assumed.

**REFITTED 2026-08-10 after failing its holdout.** The analytic form below,
`base_per_slot * padded_batch(n) + token_slope * tokens`, was fitted to e02 at
output_len=8 and returned MAPE 105.7% against a 15%-per-cell rule when e40 ran
it on hardware — it predicted 34.25 ms/req for `promote` against 11.54 measured.
e04 identified the cause: the +62 ms step at the 8->16 request-ladder edge is
real at output_len=8 and absent at output_len=1, which is what e40 runs.

What 785 measured dispatches show instead (prompt_len=512, output_len=1):

    n= 1    512 tok    13.15 ms    25.7 us/token
    n= 4   2048 tok    39.22 ms    19.2
    n= 8   4096 tok    69.08 ms    16.9
    n=16   8192 tok   145.58 ms    17.8

**Cost is sublinear in tokens.** A token costs 25.7 us alone and 16.9 us inside
a batch of eight, and that — not a ladder step — is where admission control's
saving comes from: identical work, fewer and larger batches. A step function
plus a linear term cannot express it, which is why the old model did not merely
mis-estimate the size of the effect but got its shape wrong.

So the default model now interpolates the measured curve
(`sim/measured_cost_curve.json`, regenerated by `scripts/refit_cost_model.py`).
Fitting a curve is less satisfying than a mechanism, and it is the honest
option while the mechanism is unknown: e04 has excluded batch splitting, and
the per-dispatch bimodality remains unexplained. The median is modelled; the
spread is not, and it surfaces as holdout error where it belongs.

The analytic constants are retained below for provenance and for e02's
output_len=8 regime, which genuinely does have a ladder step.

Every constant here traces to a captured run, and each carries how well it is
supported. That matters because the simulator's conclusions are only as good as
this file, and two of these parameters are much better supported than the rest.

Provenance: captured/session3/results/e02_stock_baseline (v5litepod-4,
Qwen3-4B, tpu_inference 0.25.0, prompt_len=512, 2026-08-09).

    n=6  pad= 8  tokens=3072  prefill= 55.85 ms
    n=7  pad= 8  tokens=3584  prefill= 74.05
    n=8  pad= 8  tokens=4096  prefill= 75.56
    n=9  pad=16  tokens=4608  prefill=137.92   <- crosses the request-ladder edge
    n=10 pad=16  tokens=5120  prefill=139.72
    n=15 pad=16  tokens=7680  prefill=150.76
    n=16 pad=16  tokens=8192  prefill=167.25   <- saturates max_num_batched_tokens
    n=18 pad=32  tokens=9216  prefill=171.86   <- saturates; needs 2 steps

KNOWN CONFOUND: at prompt_len=512, n=16 puts exactly 8192 tokens in flight,
which is `max_num_batched_tokens`. Cells at or above that are excluded from all
fits — they measure the token budget, not the request ladder.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

# --- WELL SUPPORTED -------------------------------------------------------
# The 8->9 discontinuity. Both cells sit well below the token budget and differ
# by one request, so the jump is attributable to the batch padding 8 -> 16.
PROMOTION_COST_MS = 60.21
# Marginal cost of real work, from the pad=16 cells below the budget (3 points).
TOKEN_SLOPE_MS_PER_TOKEN = 4.18e-3

# The ratio that motivates the whole admission question: the 9th request needs
# 2.14 ms of its own work and triggers 60.21 ms of padding.
PROMOTION_TO_WORK_RATIO = 28.1

# --- WEAKLY SUPPORTED — treat as uncertain, sweep in sensitivity ----------
# Within pad=8 the implied slope is ~19 ms/1k tokens, 4.6x the pad=16 slope.
# Three points, one of which (n=7) looks anomalous. Not used for headline
# numbers; recorded so nobody silently assumes a single global slope.
PAD8_SLOPE_MS_PER_TOKEN = 1.92e-2
SLOPE_UNCERTAINTY = (4.18e-3, 1.92e-2)

# Batch-size ladder vLLM reported on hardware (identical across both session-1
# runs and unaffected by VLLM_TPU_BUCKET_PADDING_GAP).
# Measured directly by M3 (2026-08-10): a 16-token step costs 6.10 ms and a
# 32-token step 6.08, so cost does not go to zero with tokens. Nearly half the
# cost of a 512-token step is this constant, which is what the sublinearity in
# the curve above — and the "batching amortisation" saving in e30/e40 — is
# actually amortising.
FIXED_STEP_COST_MS = 6.11

REQUEST_LADDER = (8, 16, 32, 64, 128, 256)
MAX_NUM_BATCHED_TOKENS = 8192


def padded_batch(n: int, ladder: tuple[int, ...] = REQUEST_LADDER) -> int:
    """The batch size actually compiled for, given n admitted requests."""
    if n <= 0:
        raise ValueError(f"n must be >= 1, got {n}")
    for b in ladder:
        if n <= b:
            return b
    return ladder[-1]


def _load_curve() -> tuple[tuple[float, float], ...]:
    """Measured knots, or () if the curve file is absent.

    Absence is not an error: `scripts/refit_cost_model.py` regenerates the file
    from captured runs, and the analytic fallback below keeps the simulator
    usable in a fresh checkout. It IS reported, because silently serving
    predictions from a superseded model is how the last holdout failure went
    unnoticed for a whole session.
    """
    p = Path(__file__).resolve().parent / "measured_cost_curve.json"
    if not p.exists():
        return ()
    data = json.loads(p.read_text())
    return tuple((float(t), float(c)) for t, c in data["knots_tokens_ms"])


MEASURED_KNOTS = _load_curve()


@dataclass(frozen=True)
class CostModel:
    """Prefill cost of one scheduling step.

    With measured `knots`, cost is a piecewise-linear interpolation of the
    measured curve against TOTAL TOKENS in the step. Without them it falls back
    to the analytic form

        cost = base_per_slot * padded_batch + token_slope * total_tokens

    which is retained for the output_len=8 regime, where e02 does show a real
    ladder step, and for provenance.

    `base_per_slot_ms` stays because `Hybrid` prices padding with it when
    deciding whether to wait. That is a POLICY parameter — the price the policy
    believes — and it is deliberately left at the value the hardware runs used,
    so simulated and measured policies remain the same policy.
    """

    base_per_slot_ms: float = PROMOTION_COST_MS / 8.0   # 8->16 adds 8 slots
    token_slope_ms: float = TOKEN_SLOPE_MS_PER_TOKEN
    ladder: tuple[int, ...] = REQUEST_LADDER
    max_batched_tokens: int = MAX_NUM_BATCHED_TOKENS
    knots: tuple[tuple[float, float], ...] = MEASURED_KNOTS

    def tokens_cost_ms(self, total_tokens: float) -> float:
        """Interpolate the measured curve at `total_tokens`.

        Below the first knot, add the measured FIXED PER-STEP COST to a linear
        term. That rule replaced linear-from-origin on 2026-08-10, when M3
        finally measured the region: a 16-token step costs 6.10 ms and a
        32-token step 6.08, so there is a 6.11 ms floor per step and
        linear-from-origin understated a 16-token step by 15x.

        It mattered. On the extrapolation, decomposing an 1808-token residual
        into 1024+512+256+16 beat one padded step by 1.85 ms; measured, it loses
        by 8.73 ms, because four steps pay the floor four times. An assumption
        this cheap to test should not have survived eight sessions.

        Above the last knot, continue at the final segment's slope; the
        simulator caps a step at `max_batched_tokens`, so that is a guard rather
        than a working regime.
        """
        k = self.knots
        if not k:
            raise ValueError("no measured knots")
        if total_tokens <= k[0][0]:
            # cost = floor + slope * tokens, anchored so it meets the first knot.
            slope = (k[0][1] - FIXED_STEP_COST_MS) / k[0][0]
            return FIXED_STEP_COST_MS + slope * total_tokens
        for (t0, c0), (t1, c1) in zip(k, k[1:]):
            if total_tokens <= t1:
                return c0 + (c1 - c0) * (total_tokens - t0) / (t1 - t0)
        (t0, c0), (t1, c1) = k[-2], k[-1]
        slope = (c1 - c0) / (t1 - t0)
        return c1 + slope * (total_tokens - t1)

    def step_cost_ms(self, n_requests: int, total_tokens: int) -> float:
        if self.knots:
            return self.tokens_cost_ms(total_tokens)
        return (self.base_per_slot_ms * padded_batch(n_requests, self.ladder)
                + self.token_slope_ms * total_tokens)

    def promotion_cost_ms(self, n_from: int, n_to: int) -> float:
        """Extra cost of admitting up to n_to instead of stopping at n_from.

        Zero when both land in the same compiled batch — the case where
        admitting more is free and waiting is pointless.
        """
        return self.base_per_slot_ms * (padded_batch(n_to, self.ladder)
                                        - padded_batch(n_from, self.ladder))

    def fits_token_budget(self, n_requests: int, prompt_len: int) -> bool:
        return n_requests * prompt_len <= self.max_batched_tokens
